### ISSUE TITLE
[Module] GoogleDNS4Magisk-IPv6

### ISSUE THREAD

**Issue by TukangM** [Magisk-Modules-Alt-Repo/submission#206]
### ID

GoogleDNS4Magisk-IPv6

### Name

GoogleDNS4Magisk-IPv6

### Description

Using the "Google DNS" DNS system-lessly! As simple as that and block ads and trackers.

### Module repository link

https://github.com/TukangM/GoogleDNS4Magisk-IPv6

### Source code link (for compiled binaries/APKs)

https://github.com/xerta555/CloudflareDNS4Magisk

**Comment by TukangM** [comment]
done

**Comment by DerGoogler** [comment]
@TukangM, if you want to hover your modules in MMRL, then you can include `mmrl.json` file.

```json
{
  "author": "TukangM",
  "contributors": ["xerta555"],
  "cover": "https://i.postimg.cc/gkhhPvjJ/google.png",
  "categories": [
    "Adblocking and Hosts Files",
    "Privacy Enhancements"
  ]
}
```

More you can read [here](https://github.com/Googlers-Repo/magisk?tab=readme-ov-file#configure-your-module-page-in-mmrl)

**Comment by TukangM** [comment]
> @TukangM, if you want to hover your modules in MMRL, then you can include a `mmrl.json` file.

oh thank you for your advice. If I intend to add mrrl.json. I will add it in the future or right now

**Comment by DerGoogler** [comment]
@TukangM, you have an typo.You wrote it `mrrl.json` but it should be `mmrl.json`

**Comment by TukangM** [comment]
done

**Comment by Atrate** [comment]
Seems you forgot to edit this to use Google's DNS (ipv4, as in the original module)
https://github.com/TukangM/GoogleDNS4Magisk-IPv6/blob/01658bee97a37a940016f454158661ba3aeb1b64/post-fs-data.sh#L37

**Comment by TukangM** [comment]
fixed

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/GoogleDNS4Magisk-IPv6 , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
